[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
ffi= true
[fuzz]
# change this to a much higher value in order to test as many possible values
runs = 256

# See more config options https://github.com/foundry-rs/foundry/tree/master/config
